-- Opdater image_r2_key og image_url for 29 øvelser med billeder i R2
UPDATE exercises SET image_r2_key = 'exercises/pshmcudiga.jpg', image_url = 'https://pub-ajax-traening-storage.r2.dev/exercises/pshmcudiga.jpg' WHERE id = 'pshmcudiga';
UPDATE exercises SET image_r2_key = 'exercises/ukugxvw4yv.jpg', image_url = 'https://pub-ajax-traening-storage.r2.dev/exercises/ukugxvw4yv.jpg' WHERE id = 'ukugxvw4yv';
UPDATE exercises SET image_r2_key = 'exercises/Afleveringer_med_finter.jpg', image_url = 'https://pub-ajax-traening-storage.r2.dev/exercises/Afleveringer_med_finter.jpg' WHERE id = 'Afleveringer med finter';
UPDATE exercises SET image_r2_key = 'exercises/qnn7v3xbz7.jpg', image_url = 'https://pub-ajax-traening-storage.r2.dev/exercises/qnn7v3xbz7.jpg' WHERE id = 'qnn7v3xbz7';
UPDATE exercises SET image_r2_key = 'exercises/w3nvsq8opz.jpg', image_url = 'https://pub-ajax-traening-storage.r2.dev/exercises/w3nvsq8opz.jpg' WHERE id = 'w3nvsq8opz';
UPDATE exercises SET image_r2_key = 'exercises/finterr_i_aben_ramme.jpg', image_url = 'https://pub-ajax-traening-storage.r2.dev/exercises/finterr_i_aben_ramme.jpg' WHERE id = 'finterr i åben ramme';
UPDATE exercises SET image_r2_key = 'exercises/finter_i_aben_ramme_med_skra_tilgang.jpg', image_url = 'https://pub-ajax-traening-storage.r2.dev/exercises/finter_i_aben_ramme_med_skra_tilgang.jpg' WHERE id = 'finter i åben ramme med skrå tilgang';
UPDATE exercises SET image_r2_key = 'exercises/586vaj750e.jpg', image_url = 'https://pub-ajax-traening-storage.r2.dev/exercises/586vaj750e.jpg' WHERE id = '586vaj750e';
UPDATE exercises SET image_r2_key = 'exercises/u1fkhwnivt.jpg', image_url = 'https://pub-ajax-traening-storage.r2.dev/exercises/u1fkhwnivt.jpg' WHERE id = 'u1fkhwnivt';
UPDATE exercises SET image_r2_key = 'exercises/2fvuzl8x62.jpg', image_url = 'https://pub-ajax-traening-storage.r2.dev/exercises/2fvuzl8x62.jpg' WHERE id = '2fvuzl8x62';
UPDATE exercises SET image_r2_key = 'exercises/qmfq2rztj2.jpg', image_url = 'https://pub-ajax-traening-storage.r2.dev/exercises/qmfq2rztj2.jpg' WHERE id = 'qmfq2rztj2';
UPDATE exercises SET image_r2_key = 'exercises/9cie97nia0.jpg', image_url = 'https://pub-ajax-traening-storage.r2.dev/exercises/9cie97nia0.jpg' WHERE id = '9cie97nia0';
UPDATE exercises SET image_r2_key = 'exercises/cm35mwu4wg.jpg', image_url = 'https://pub-ajax-traening-storage.r2.dev/exercises/cm35mwu4wg.jpg' WHERE id = 'cm35mwu4wg';
UPDATE exercises SET image_r2_key = 'exercises/elchmsv18y.jpg', image_url = 'https://pub-ajax-traening-storage.r2.dev/exercises/elchmsv18y.jpg' WHERE id = 'elchmsv18y';
UPDATE exercises SET image_r2_key = 'exercises/j1xhr28djw.jpg', image_url = 'https://pub-ajax-traening-storage.r2.dev/exercises/j1xhr28djw.jpg' WHERE id = 'j1xhr28djw';
UPDATE exercises SET image_r2_key = 'exercises/mku7mao03asmmt68ybi.jpg', image_url = 'https://pub-ajax-traening-storage.r2.dev/exercises/mku7mao03asmmt68ybi.jpg' WHERE id = 'mku7mao03asmmt68ybi';
UPDATE exercises SET image_r2_key = 'exercises/f58oauyrk6immuii50t.jpg', image_url = 'https://pub-ajax-traening-storage.r2.dev/exercises/f58oauyrk6immuii50t.jpg' WHERE id = 'f58oauyrk6immuii50t';
UPDATE exercises SET image_r2_key = 'exercises/95b8i9isvnemn4un4v6.jpg', image_url = 'https://pub-ajax-traening-storage.r2.dev/exercises/95b8i9isvnemn4un4v6.jpg' WHERE id = '95b8i9isvnemn4un4v6';
UPDATE exercises SET image_r2_key = 'exercises/cup63ikgfzgmn5yhn8d.jpg', image_url = 'https://pub-ajax-traening-storage.r2.dev/exercises/cup63ikgfzgmn5yhn8d.jpg' WHERE id = 'cup63ikgfzgmn5yhn8d';
UPDATE exercises SET image_r2_key = 'exercises/5xyur0r6e27mng0m1lh.jpg', image_url = 'https://pub-ajax-traening-storage.r2.dev/exercises/5xyur0r6e27mng0m1lh.jpg' WHERE id = '5xyur0r6e27mng0m1lh';
UPDATE exercises SET image_r2_key = 'exercises/jfe1pq8yhnkmng1fdef.jpg', image_url = 'https://pub-ajax-traening-storage.r2.dev/exercises/jfe1pq8yhnkmng1fdef.jpg' WHERE id = 'jfe1pq8yhnkmng1fdef';
UPDATE exercises SET image_r2_key = 'exercises/b5lnkvi646tmng27li4.jpg', image_url = 'https://pub-ajax-traening-storage.r2.dev/exercises/b5lnkvi646tmng27li4.jpg' WHERE id = 'b5lnkvi646tmng27li4';
UPDATE exercises SET image_r2_key = 'exercises/tekrxizhz6nmng4pa8i.jpg', image_url = 'https://pub-ajax-traening-storage.r2.dev/exercises/tekrxizhz6nmng4pa8i.jpg' WHERE id = 'tekrxizhz6nmng4pa8i';
UPDATE exercises SET image_r2_key = 'exercises/wtjcwjpvz0imng50g63.jpg', image_url = 'https://pub-ajax-traening-storage.r2.dev/exercises/wtjcwjpvz0imng50g63.jpg' WHERE id = 'wtjcwjpvz0imng50g63';
UPDATE exercises SET image_r2_key = 'exercises/65ekltnwfglmng52i93.jpg', image_url = 'https://pub-ajax-traening-storage.r2.dev/exercises/65ekltnwfglmng52i93.jpg' WHERE id = '65ekltnwfglmng52i93';
UPDATE exercises SET image_r2_key = 'exercises/0vmmql7d43pmng5afrp.jpg', image_url = 'https://pub-ajax-traening-storage.r2.dev/exercises/0vmmql7d43pmng5afrp.jpg' WHERE id = '0vmmql7d43pmng5afrp';
UPDATE exercises SET image_r2_key = 'exercises/pri603l2unmng5er27.jpg', image_url = 'https://pub-ajax-traening-storage.r2.dev/exercises/pri603l2unmng5er27.jpg' WHERE id = 'pri603l2unmng5er27';
UPDATE exercises SET image_r2_key = 'exercises/3dhtjpva1mbmng5gosv.jpg', image_url = 'https://pub-ajax-traening-storage.r2.dev/exercises/3dhtjpva1mbmng5gosv.jpg' WHERE id = '3dhtjpva1mbmng5gosv';
UPDATE exercises SET image_r2_key = 'exercises/3obpet2zvl2mng5j4rf.jpg', image_url = 'https://pub-ajax-traening-storage.r2.dev/exercises/3obpet2zvl2mng5j4rf.jpg' WHERE id = '3obpet2zvl2mng5j4rf';